source "https://rubygems.org"

gem "kingfisher", path: "/Users/halogenandtoast/Code/ruby/kingfisher"
gem "sequel"
gem "puma"
gem "rack"
gem "sqlite3"
gem "slim"
gem "pry"
gem "warden"
gem "bcrypt"
gem "rspec"
gem "capybara"
gem "dotenv"
gem "pg"
